In [3]:
from PIL import Image
img=Image.open("F:\\acess_ieee\\jinna-acess-exp\\layer\\test\\387.jpg")
l=img.crop((0,0,256,256))
# crop=img.crop((0,0,512,256))
r=img.crop((256,0,512,256))
l.save("F:\\acess_ieee\\jinna-acess-exp\\layer\\test\\387_left.png")
r.save("F:\\acess_ieee\\jinna-acess-exp\\layer\\test\\387_right.png")

In [4]:
import numpy as np
ones=np.ones([2,3])
gram = np.matmul(ones.T, ones) / ones.size

In [5]:
print(gram)

[[ 0.33333333  0.33333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]]


In [6]:
print(np.matmul(ones.T, ones))

[[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]
